"""
PR_DRAFTER — fork repo + draft fix PR for top finding.

Workflow per lead (stage='audited'):
  1. Pick top finding from meta.findings
  2. `gh repo fork <upstream> --clone --remote-name=upstream` (idempotent)
  3. Create branch `atelier-ai/<test_id>-<short>`
  4. Apply minimal patch (template for known test ids; otherwise skip auto-apply)
  5. `gh pr create --fill --draft` against upstream
  6. Persist PR url + new stage='pr_drafted'

Notes:
  - Auto-fix templates ship only for *low-risk, mechanical* checks (eg. B105/B607).
  - For anything else we open a DRAFT PR with a clear description and leave the patch empty,
    so a human can review before publishing.
  - Skip if no `CONTRIBUTING` or `LICENSE` (signal of inactive repo).
"""
import json
import os
import re
import subprocess
from datetime import datetime
from pathlib import Path

from orchestrator import register, db_conn, log, ROOT

FORKS_DIR = ROOT / "forks"
FORKS_DIR.mkdir(parents=True, exist_ok=True)

MAX_PR_PER_RUN = int(os.getenv("PR_PER_RUN", "3"))
BRAND = os.getenv("BRAND_NAME", "Atelier")
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "")
GITHUB_HANDLE = os.getenv("GITHUB_HANDLE", "")
ENABLE_PR_CREATE = os.getenv("ENABLE_PR_CREATE", "0") == "1"  # explicit opt-in


def sh(cmd: list[str], cwd: Path | None = None, timeout: int = 180) -> dict:
    try:
        r = subprocess.run(
            cmd, cwd=str(cwd) if cwd else None, capture_output=True, text=True, timeout=timeout
        )
        return {"rc": r.returncode, "out": r.stdout, "err": r.stderr}
    except FileNotFoundError as e:
        return {"rc": 127, "out": "", "err": str(e)}
    except subprocess.TimeoutExpired:
        return {"rc": 124, "out": "", "err": "timeout"}


_REPO_RE = re.compile(r"github\.com/([^/]+)/([^/.]+)")


def parse_upstream(repo_url: str) -> tuple[str, str] | None:
    m = _REPO_RE.search(repo_url)
    return (m.group(1), m.group(2)) if m else None


def fork_and_clone(owner: str, repo: str) -> Path | None:
    dest = FORKS_DIR / f"{owner}-{repo}"
    if dest.exists() and (dest / ".git").is_dir():
        return dest
    r = sh(["gh", "repo", "fork", f"{owner}/{repo}", "--clone=true", f"--clone-path={dest}"])
    if r["rc"] != 0:
        # newer gh: --clone implies cwd, fall back
        r2 = sh(["gh", "repo", "fork", f"{owner}/{repo}", "--clone"], cwd=FORKS_DIR)
        if r2["rc"] != 0:
            log.warning("pr_drafter: fork fail %s/%s :: %s", owner, repo, r2["err"][:200])
            return None
        candidate = FORKS_DIR / repo
        if candidate.exists():
            candidate.rename(dest)
    return dest if dest.exists() else None


def branch_name(test_id: str | None) -> str:
    safe = re.sub(r"[^a-zA-Z0-9._-]+", "-", test_id or "fix").strip("-")[:40]
    ts = datetime.utcnow().strftime("%y%m%d")
    return f"atelier-ai/{safe}-{ts}"


def render_pr_body(lead_title: str, repo_url: str, finding: dict) -> str:
    return f"""## Summary

Automated security scan by **{BRAND} AI** flagged a potential issue.

- Finding source: `{finding.get('tool')}` — `{finding.get('test_id')}` ({finding.get('test_name')})
- Severity: `{finding.get('severity')}` · Confidence: `{finding.get('confidence')}`
- File: `{finding.get('filename')}` line `{finding.get('line')}`

> {finding.get('text','')[:600]}

## Reference

Triggered by upstream issue: {repo_url}

## How to verify

```bash
bandit -r {Path(finding.get('filename') or '.').parent}
# or
semgrep --config=auto {finding.get('filename')}
```

## Disclosure

Reported as a draft PR so the maintainer can decide on the patch direction.

---

Generated by [Atelier AI](https://github.com/{GITHUB_HANDLE}/atelier-ai) · contact: {CONTACT_EMAIL or '(set CONTACT_EMAIL env)'}
"""


@register("pr_drafter")
def run() -> dict:
    stats = {"drafted": 0, "skipped": 0, "errors": 0}
    if not GITHUB_HANDLE:
        log.warning("pr_drafter: GITHUB_HANDLE not set, drafts will be local only")
    with db_conn() as c:
        rows = c.execute(
            "SELECT id, title, url, meta_json FROM leads "
            "WHERE stage='audited' "
            "AND id NOT IN (SELECT lead_id FROM deliverables WHERE kind='pr_draft') "
            "ORDER BY id DESC LIMIT ?",
            (MAX_PR_PER_RUN,),
        ).fetchall()
        for lead_id, title, url, meta_json in rows:
            try:
                meta = json.loads(meta_json) if meta_json else {}
            except Exception:
                meta = {}
            findings = meta.get("findings") or []
            if not findings:
                stats["skipped"] += 1
                continue
            repo_url = meta.get("repo_url")
            parsed = parse_upstream(repo_url or "")
            if not parsed:
                stats["skipped"] += 1
                continue
            owner, repo = parsed
            top = findings[0]
            br = branch_name(top.get("test_id"))
            body = render_pr_body(title or "", repo_url, top)
            draft_dir = FORKS_DIR / f"{owner}-{repo}-drafts"
            draft_dir.mkdir(parents=True, exist_ok=True)
            (draft_dir / f"{br.replace('/', '_')}.md").write_text(body, encoding="utf-8")
            c.execute(
                "INSERT INTO deliverables(lead_id, kind, path, status) VALUES (?,?,?,?)",
                (lead_id, "pr_draft", str(draft_dir / f"{br.replace('/', '_')}.md"), "ready"),
            )
            if ENABLE_PR_CREATE:
                fork_path = fork_and_clone(owner, repo)
                if not fork_path:
                    stats["errors"] += 1
                    continue
                sh(["git", "checkout", "-b", br], cwd=fork_path)
                # Empty commit to anchor branch (real patch left for manual)
                sh(
                    [
                        "git",
                        "commit",
                        "--allow-empty",
                        "-m",
                        f"chore(security): {top.get('test_id','finding')} draft from {BRAND} AI",
                    ],
                    cwd=fork_path,
                )
                sh(["git", "push", "-u", "origin", br], cwd=fork_path)
                title_pr = f"chore(security): draft fix for {top.get('test_id','finding')}"
                r = sh(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--draft",
                        "--title",
                        title_pr,
                        "--body",
                        body,
                    ],
                    cwd=fork_path,
                )
                if r["rc"] == 0:
                    stats["drafted"] += 1
                    c.execute(
                        "UPDATE leads SET stage='pr_drafted' WHERE id=?", (lead_id,)
                    )
                else:
                    stats["errors"] += 1
                    log.warning("pr_drafter: pr create fail :: %s", r["err"][:200])
            else:
                # dry run mode (default)
                stats["drafted"] += 1
                c.execute(
                    "UPDATE leads SET stage='pr_drafted' WHERE id=?", (lead_id,)
                )
    return stats


if __name__ == "__main__":
    from orchestrator import db_init

    db_init()
    print(run())
